version: '3.8'
services:
  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    image: notification-service
    container_name: notification-service
    networks:
      - digital-wallet-network
    environment:
      - OTEL_SERVICE_NAME=notification-service
      - OTEL_TRACES_EXPORTER=jaeger
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14250
      - OTEL_METRICS_EXPORTER=none
      - OTEL_EXPORTER_JAEGER_TIMEOUT=40000
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14250:14250"
    networks:
      - digital-wallet-network
  prometheus:
    image: prom/prometheus
    container_name: prometheus-container
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: always
    networks:
      - digital-wallet-network
  grafana:
    image: grafana/grafana
    user: "$UID:$GID"
    container_name: grafana-container
    ports:
      - "3003:3000"
    volumes:
      - ./grafana/:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=admin
    networks:
      - digital-wallet-network
networks:
  digital-wallet-network: {}
